#!/bin/bash -f
#==============================================================================
# RISC CPU - Innovus Place & Route
# Usage: ./go_pnr
#==============================================================================

cd /home/share_file/cadence
source add_path
source add_license
cd -

innovus -files scripts/pnr.tcl &
